### ISSUE TITLE
Change bookmarklet to lead to pop-up rather than new tab

### ISSUE THREAD

**Issue by dajbelshaw** [toolness/weblitmapper#18] opened 2014-03-27 10:03 UTC
Feedback from etherpad: "I'm a big fan of the Persona window UX; if there's a way to shrink the tagging page and make it come up and kind of go away after confirming a submission with clean animation, etc., I'd like that more than another tab."

https://etherpad.mozilla.org/weblitmapper-feedback

**Comment by toolness** [comment] 2014-03-27 12:33
Ok, I've just modified the bookmarklet to open in a window instead of a new tab--can you try this out and let me know if it helps?

Still need to make the page go away after confirming the submission though, hrm.

**Comment by dajbelshaw** [comment] 2014-03-31 09:29
Looks good. If the page could go away and then return you to the WebLitMapper home page (the gallery) that would be awesome.

**Comment by toolness** [comment] 2014-05-13 18:34
Oh, it turns out #31 was a duplicate of this! And that's fixed now, thanks to FuzzyFox, so this is too :)

**Closed as completed by toolness** 2014-05-13 18:34 UTC
